package org.katas.refactoring.fizzbuzz;

import org.junit.Test;

import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;

public class FizzBuzzSmokeTest {
    @Test
    public void should_smoke_test_pass_when_fizz_buzz_given_200_numbers() {
        String expected = "1\n" +
            "2\n" +
            "Fizz\n" +
            "4\n" +
            "Buzz\n" +
            "Fizz\n" +
            "Whizz\n" +
            "8\n" +
            "Fizz\n" +
            "Buzz\n" +
            "11\n" +
            "Fizz\n" +
            "Fizz\n" +
            "Whizz\n" +
            "FizzBuzz\n" +
            "16\n" +
            "17\n" +
            "Fizz\n" +
            "19\n" +
            "Buzz\n" +
            "FizzWhizz\n" +
            "22\n" +
            "Fizz\n" +
            "Fizz\n" +
            "Buzz\n" +
            "26\n" +
            "Fizz\n" +
            "Whizz\n" +
            "29\n" +
            "Fizz\n" +
            "Fizz\n" +
            "Fizz\n" +
            "Fizz\n" +
            "Fizz\n" +
            "Fizz\n" +
            "Fizz\n" +
            "Fizz\n" +
            "Fizz\n" +
            "Fizz\n" +
            "Buzz\n" +
            "41\n" +
            "FizzWhizz\n" +
            "Fizz\n" +
            "44\n" +
            "FizzBuzz\n" +
            "46\n" +
            "47\n" +
            "Fizz\n" +
            "Whizz\n" +
            "Buzz\n" +
            "Fizz\n" +
            "52\n" +
            "Fizz\n" +
            "Fizz\n" +
            "Buzz\n" +
            "Whizz\n" +
            "Fizz\n" +
            "58\n" +
            "59\n" +
            "FizzBuzz\n" +
            "61\n" +
            "62\n" +
            "Fizz\n" +
            "64\n" +
            "Buzz\n" +
            "Fizz\n" +
            "67\n" +
            "68\n" +
            "Fizz\n" +
            "BuzzWhizz\n" +
            "71\n" +
            "Fizz\n" +
            "Fizz\n" +
            "74\n" +
            "FizzBuzz\n" +
            "76\n" +
            "Whizz\n" +
            "Fizz\n" +
            "79\n" +
            "Buzz\n" +
            "Fizz\n" +
            "82\n" +
            "Fizz\n" +
            "FizzWhizz\n" +
            "Buzz\n" +
            "86\n" +
            "Fizz\n" +
            "88\n" +
            "89\n" +
            "FizzBuzz\n" +
            "Whizz\n" +
            "92\n" +
            "Fizz\n" +
            "94\n" +
            "Buzz\n" +
            "Fizz\n" +
            "97\n" +
            "Whizz\n" +
            "Fizz\n" +
            "Buzz\n" +
            "101\n" +
            "Fizz\n" +
            "Fizz\n" +
            "104\n" +
            "FizzBuzzWhizz\n" +
            "106\n" +
            "107\n" +
            "Fizz\n" +
            "109\n" +
            "Buzz\n" +
            "Fizz\n" +
            "Whizz\n" +
            "Fizz\n" +
            "Fizz\n" +
            "Buzz\n" +
            "116\n" +
            "Fizz\n" +
            "118\n" +
            "Whizz\n" +
            "FizzBuzz\n" +
            "121\n" +
            "122\n" +
            "Fizz\n" +
            "124\n" +
            "Buzz\n" +
            "FizzWhizz\n" +
            "127\n" +
            "128\n" +
            "Fizz\n" +
            "Fizz\n" +
            "Fizz\n" +
            "Fizz\n" +
            "Fizz\n" +
            "Fizz\n" +
            "Fizz\n" +
            "Fizz\n" +
            "Fizz\n" +
            "Fizz\n" +
            "Fizz\n" +
            "BuzzWhizz\n" +
            "Fizz\n" +
            "142\n" +
            "Fizz\n" +
            "Fizz\n" +
            "Buzz\n" +
            "146\n" +
            "FizzWhizz\n" +
            "148\n" +
            "149\n" +
            "FizzBuzz\n" +
            "151\n" +
            "152\n" +
            "Fizz\n" +
            "Whizz\n" +
            "Buzz\n" +
            "Fizz\n" +
            "157\n" +
            "158\n" +
            "Fizz\n" +
            "Buzz\n" +
            "Whizz\n" +
            "Fizz\n" +
            "Fizz\n" +
            "164\n" +
            "FizzBuzz\n" +
            "166\n" +
            "167\n" +
            "FizzWhizz\n" +
            "169\n" +
            "Buzz\n" +
            "Fizz\n" +
            "172\n" +
            "Fizz\n" +
            "Fizz\n" +
            "BuzzWhizz\n" +
            "176\n" +
            "Fizz\n" +
            "178\n" +
            "179\n" +
            "FizzBuzz\n" +
            "181\n" +
            "Whizz\n" +
            "Fizz\n" +
            "184\n" +
            "Buzz\n" +
            "Fizz\n" +
            "187\n" +
            "188\n" +
            "FizzWhizz\n" +
            "Buzz\n" +
            "191\n" +
            "Fizz\n" +
            "Fizz\n" +
            "194\n" +
            "FizzBuzz\n" +
            "Whizz\n" +
            "197\n" +
            "Fizz\n" +
            "199\n" +
            "Buzz\n";

        FizzBuzz fizzBuzz = new FizzBuzz();
        StringBuilder actual = new StringBuilder();
        for (int i = 0; i < 200; i++) {
            actual.append(fizzBuzz.sayIt(i + 1)).append("\n");
        }

        assertThat(expected, is(actual.toString()));
    }
}
